In [2]:
import numpy as np

stats = {
    "weight": (80, 12),
    "hr": (72, 8),
    "bp": (124, 13),
    "hb1ac": (6.2, 1.0)
}

def initialize_states(n, seed=42):
    rng = np.random.default_rng(seed)
    weight = rng.normal(80, 12, n)
    hr = rng.normal(72, 8, n)
    bp = rng.normal(124, 13, n)
    hba1c = rng.normal(6.2, 1.0, n)
    X = np.column_stack([weight, hr, bp, hba1c])
    return X

def compute_badness_by_sd(X, cap_sd=3):
    """
    Compute badness based on how many SDs away from mean each vital is.
    cap_sd: beyond this, badness=1.
    """
    names = list(stats.keys())
    n, p = X.shape
    bad = np.zeros_like(X)
    
    for j, name in enumerate(names):
        mu, sigma = stats[name]
        z = np.abs(X[:, j] - mu) / sigma   # deviation in SDs
        bad[:, j] = np.clip(z / cap_sd, 0, 1)  # 0 to 1 scaled
    return bad

# Example
n = 5
S0 = initialize_states(n)
badness = compute_badness_by_sd(S0)

print("Vitals:\n", S0)
print("\nBadness (0 healthy → 1 unhealthy):\n", badness)

Vitals:
 [[ 83.65660496  61.58256395 135.43217367   5.34070754]
 [ 67.52019073  73.02272323 134.11129516   6.56875078]
 [ 89.00541435  69.47005926 124.85839907   5.2411174 ]
 [ 91.2867766   71.86559074 138.65413569   7.0784503 ]
 [ 56.58757774  65.17564858 130.07762145   6.15007409]]

Badness (0 healthy → 1 unhealthy):
 [[0.10157236 0.43405984 0.29313266 0.28643082]
 [0.34666137 0.04261347 0.25926398 0.12291693]
 [0.2501504  0.1054142  0.02201023 0.31962753]
 [0.31352157 0.00560039 0.37574707 0.29281677]
 [0.65034506 0.28434798 0.15583645 0.01664197]]
